---
# Phoenix VirtualService (Istio)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: phoenix-vs
  namespace: istio-system
spec:
  hosts:
    - phoenix.aws11.shop
  gateways:
    - main-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: phoenix-service.default.svc.cluster.local
            port:
              number: 6006
